INSERT INTO users (email, username, password, created_at)
VALUES ("admin@admin.com", "Antoine", "$2a$10$abvkwuywxm/3DXVaMwj6rueAHYpxeHRAEkak2JCeHAc/OsIwHlSNG", "2024-01-01 00:00:00"), ("user@user.com", "Thomas", "$2a$10$abvkwuywxm/3DXVaMwj6rueAHYpxeHRAEkak2JCeHAc/OsIwHlSNG", "2024-01-01 00:00:00");

INSERT INTO topics (name, description, created_at)
VALUES ("Front-End", "Front Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "2024-01-01 00:00:00"),
("Back-End", "Back Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "2024-01-01 00:00:00"),
("Testing", "Testing Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "2024-01-01 00:00:00"),
("Java", "Java Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "2024-01-01 00:00:00"),
("Angular", "Angular Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit.", "2024-01-01 00:00:00");

INSERT INTO posts (content, title, author_id, created_at)
VALUES ("Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor.","Titre 1", 1, "2024-01-01 00:00:00"),
       ("Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor.", "Titre 2", 2, "2024-01-01 00:00:00"),
       ("Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor.", "Titre 3", 1, "2024-01-01 00:00:00"),
       ("Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor.", "Titre 4", 2, "2024-01-01 00:00:00"),
       ("Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum ut ipsam optio et itaque, fugit accusantium sed soluta saepe ipsa, laborum minima sunt odit, quos magni! Itaque vel nihil dolor.", "Titre 5", 1, "2024-01-01 00:00:00");

INSERT INTO topics_posts (topic_id, post_id)
VALUES (3, 1),
       (1, 2),
       (2, 3),
       (3, 4),
       (2, 5),
       (1, 3);

INSERT INTO comments (content, author_id, post_id, created_at)
VALUES ("Premier commentaire du site", 1, 1, "2024-01-01 00:00:00"),
       ("Deuxième commentaire du site", 2, 1, "2024-01-01 00:00:00"),
       ("Troisième commentaire du site", 2, 2, "2024-01-01 00:00:00"),
       ("Quatrième commentaire du site", 1, 3, "2024-01-01 00:00:00");